// ref: https://docusaurus.io/docs/sidebar/multiple-sidebars#generating-pagination
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link margin-left-minus-10" target="_blank" rel="noopener noreferrer" href="/media-kit.pdf">Media Kit</a>',
      defaultStyle: true,
    },
  ],
}

module.exports = sidebars
